// Generated by tools/gen_ios_vectors.py — do not edit by hand.
// Independent reference values for the crypto layer (see ios/docs/vectors.md).
import Foundation

enum TestVectors {
    static let mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
    static let passphrase = "TREZOR"
    static let seedTrezor = "c55257c360c07c72029aebc1b53c05ed0362ada38ead3e3e9efa3708e53495531f09a6987599d18264c1e1c92f2cf141630c7a3c4ab7c81b2f001698e7463b04"
    static let seedNoPassphrase = "5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc19a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4"
    static let wordlistSHA256 = "187db04a869dd9bc7be80d21a86497d692c0db6abd3aa8cb6be5d618ff757fae"
    static let wordlistFirst = "abandon"
    static let wordlistLast = "zoo"
    static let indexAbout = 3

    // MARK: BIP-32
    static let bip32Seed1 = "000102030405060708090a0b0c0d0e0f"
    static let bip32MasterXprv = "xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBxrMPHi"
    static let bip32MasterXpub = "xpub661MyMwAqRbcFtXgS5sYJABqqG9YLmC4Q1Rdap9gSE8NqtwybGhePY2gZ29ESFjqJoCu1Rupje8YtGqsefD265TMg7usUDFdp6W1EGMcet8"
    static let bip32MasterChainCode = "873dff81c02f525623fd1fe5167eac3a55a049de3d314bb42ee227ffed37d508"
    static let bip32MasterPrivHex = "e8f32e723decf4051aefac8e2c93c9c5b214313817cdb01a1494b917c8436b35"
    static let bip32ChildXprv = "xprv9uHRZZhk6KAJC1avXpDAp4MDc3sQKNxDiPvvkX8Br5ngLNv1TxvUxt4cV1rGL5hj6KCesnDYUhd7oWgT11eZG7XnxHrnYeSvkzY7d2bhkJ7"
    static let bip32ChildXpub = "xpub68Gmy5EdvgibQVfPdqkBBCHxA5htiqg55crXYuXoQRKfDBFA1WEjWgP6LHhwBZeNK1VTsfTFUHCdrfp1bgwQ9xv5ski8PX9rL2dZXvgGDnw"
    static let bip32Vector2MasterXpub = "xpub661MyMwAqRbcFW31YEwpkMuc5THy2PSt5bDMsktWQcFF8syAmRUapSCGu8ED9W6oDMSgv6Zz8idoc4a6mr8BDzTJY47LJhkJ8UB7WEGuduB"

    // MARK: BIP-32 test vector 1, deeper chains (hardened and normal steps)
    static let bip32DeepChain: [(path: String, xprv: String, xpub: String)] = [
        ("m/0'", "xprv9uHRZZhk6KAJC1avXpDAp4MDc3sQKNxDiPvvkX8Br5ngLNv1TxvUxt4cV1rGL5hj6KCesnDYUhd7oWgT11eZG7XnxHrnYeSvkzY7d2bhkJ7", "xpub68Gmy5EdvgibQVfPdqkBBCHxA5htiqg55crXYuXoQRKfDBFA1WEjWgP6LHhwBZeNK1VTsfTFUHCdrfp1bgwQ9xv5ski8PX9rL2dZXvgGDnw"),
        ("m/0'/1", "xprv9wTYmMFdV23N2TdNG573QoEsfRrWKQgWeibmLntzniatZvR9BmLnvSxqu53Kw1UmYPxLgboyZQaXwTCg8MSY3H2EU4pWcQDnRnrVA1xe8fs", "xpub6ASuArnXKPbfEwhqN6e3mwBcDTgzisQN1wXN9BJcM47sSikHjJf3UFHKkNAWbWMiGj7Wf5uMash7SyYq527Hqck2AxYysAA7xmALppuCkwQ"),
        ("m/0'/1/2'", "xprv9z4pot5VBttmtdRTWfWQmoH1taj2axGVzFqSb8C9xaxKymcFzXBDptWmT7FwuEzG3ryjH4ktypQSAewRiNMjANTtpgP4mLTj34bhnZX7UiM", "xpub6D4BDPcP2GT577Vvch3R8wDkScZWzQzMMUm3PWbmWvVJrZwQY4VUNgqFJPMM3No2dFDFGTsxxpG5uJh7n7epu4trkrX7x7DogT5Uv6fcLW5"),
        ("m/0'/1/2'/2", "xprvA2JDeKCSNNZky6uBCviVfJSKyQ1mDYahRjijr5idH2WwLsEd4Hsb2Tyh8RfQMuPh7f7RtyzTtdrbdqqsunu5Mm3wDvUAKRHSC34sJ7in334", "xpub6FHa3pjLCk84BayeJxFW2SP4XRrFd1JYnxeLeU8EqN3vDfZmbqBqaGJAyiLjTAwm6ZLRQUMv1ZACTj37sR62cfN7fe5JnJ7dh8zL4fiyLHV"),
        ("m/0'/1/2'/2/1000000000", "xprvA41z7zogVVwxVSgdKUHDy1SKmdb533PjDz7J6N6mV6uS3ze1ai8FHa8kmHScGpWmj4WggLyQjgPie1rFSruoUihUZREPSL39UNdE3BBDu76", "xpub6H1LXWLaKsWFhvm6RVpEL9P4KfRZSW7abD2ttkWP3SSQvnyA8FSVqNTEcYFgJS2UaFcxupHiYkro49S8yGasTvXEYBVPamhGW6cFJodrTHy"),
    ]

    // MARK: addresses for the abandon…about mnemonic
    static let btcLegacyAddress = "1LqBGSKuX5yYUonjxT5qGfpUsXKYYWeabA"
    static let btcLegacyPath = "m/44'/0'/0'/0/0"
    static let btcP2SHAddress = "37VucYSaXLCAsxYyAPfbSi9eh4iEcbShgf"
    static let btcP2SHPath = "m/49'/0'/0'/0/0"
    static let btcSegwitAddress = "bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu"
    static let btcSegwitPath = "m/84'/0'/0'/0/0"
    static let btcTaprootAddress = "bc1p5cyxnuxmeuwuvkwfem96lqzszd02n6xdcjrs20cac6yqjjwudpxqkedrcr"
    static let btcTaprootPath = "m/86'/0'/0'/0/0"
    static let ethAddress = "0x9858EfFD232B4033E47d90003D41EC34EcaEda94"
    static let ethPath = "m/44'/60'/0'/0/0"
    static let solanaAddress = "4nFZgXtZAEwbfA56LRVRdsDGNeW3U55gr5hL9c5E5de5"
    static let solanaPath = "m/44'/501'/0'/0'"
    static let btcTaprootOutputKey = "a60869f0dbcf1dc659c9cecbaf8050135ea9e8cdc487053f1dc6880949dc684c"
    static let bip84AccountXprv = "zprvAdG4iTXWBoARxkkzNpNh8r6Qag3irQB8PzEMkAFeTRXxHpbF9z4QgEvBRmfvqWvGp42t42nvgGpNgYSJA9iefm1yYNZKEm7z6qUWCroSQnE"
    static let bip84AccountXpub = "zpub6rFR7y4Q2AijBEqTUquhVz398htDFrtymD9xYYfG1m4wAcvPhXNfE3EfH1r1ADqtfSdVCToUG868RvUUkgDKf31mGDtKsAYz2oz2AGutZYs"
    static let bip84Hash160 = "c0cebcd6c3d3ca8c75dc5ec62ebe55330ef910e2"
    static let wif = "5KY3dHRWNnFkBJaTnmUTaR1oqs9tU9goQbG19FSNLSo5oAxLokG"
    static let wifCompressed = "L4p2b9VAf8k5aUahF1JCJUzZkgNEAqLfq8DDdQiyAprQAKSbu8hf"
    static let privHex = "e284129cc0922579a535bbf4d1a3b25773090d28c909bc0fed73b5e0222cc372"

    // MARK: hashes
    static let keccak: [(String, String)] = [
        ("", "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"),
        ("abc", "4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45"),
        ("The quick brown fox jumps over the lazy dog", "4d741b6f1eb29cb2a9b9911c82f56fa8d73b04959d3d9d222895df6c0b28aa15"),
    ]

    static let ripemd: [(String, String)] = [
        ("", "9c1185a5c5e9fc54612808977ee8f548b2258d31"),
        ("abc", "8eb208f7e05d987a9b044a8e98c6b087f15a0bfc"),
    ]

    static let sha256: [(String, String)] = [
        ("", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"),
        ("abc", "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"),
    ]

    static let sha512: [(String, String)] = [
        ("abc", "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f"),
        ("abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq", "204a8fc6dda82f0a0ced7beb8e08a41657c16ef468b228a8279be331a703c33596fd15c13b1b07f9aa1d3bea57789ca031ad85c7a71dd70354ec631238ca3445"),
    ]



    // MARK: base58check
    static let base58check = (version: "00", payload: "d986ed01b7a22225a70edbf2ba7cfb63a15cb3aa", out: "1LqBGSKuX5yYUonjxT5qGfpUsXKYYWeabA")

    // MARK: bech32 (BIP-173 reference lists)

    static let bech32Valid: [String] = [
        "A12UEL5L",
        "a12uel5l",
        "an83characterlonghumanreadablepartthatcontainsthenumber1andtheexcludedcharactersbio1tt5tgs",
        "abcdef1qpzry9x8gf2tvdw0s3jn54khce6mua7lmqqqxw",
        "11qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8247j",
        "split1checkupstagehandshakeupstreamerranterredcaperred2y9e3w",
        "?1ezyfcl",
    ]

    static let bech32Invalid: [String] = [
        " 1nwldj5",
        "\u{7f}1axkwrx",
        "1eym55h",
        "an84characterslonghumanreadablepartthatcontainsthenumber1andtheexcludedcharactersbio1569pvx",
        "pzry9x0s0muk",
        "1pzry9x0s0muk",
        "x1b4n0q5v",
        "li1dgmt3",
        "de1lg7wtÿ",
        "A1G7SGD8",
        "10a06t8",
        "1qzzfhee",
    ]

    // MARK: credential parsing

    struct PhraseCase: Sendable { let phrase: String; let valid: Bool; let reason: String? }
    static let phraseCases: [PhraseCase] = [
        PhraseCase(phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about", valid: true, reason: nil),
        PhraseCase(phrase: "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo wrong", valid: true, reason: nil),
        PhraseCase(phrase: "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo ", valid: false, reason: "checksum"),
        PhraseCase(phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon ", valid: false, reason: "checksum"),
        PhraseCase(phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon zzz", valid: false, reason: "unknown word"),
        PhraseCase(phrase: "abandon about", valid: false, reason: "word count"),
    ]

    // MARK: pbkdf2-hmac-sha512

    struct PBKDF2Case: Sendable { let password: String; let salt: String; let iterations: Int; let length: Int; let out: String }
    static let pbkdf2Cases: [PBKDF2Case] = [
        PBKDF2Case(password: "password", salt: "salt", iterations: 1, length: 64, out: "867f70cf1ade02cff3752599a3a53dc4af34c7a669815ae5d513554e1c8cf252c02d470a285a0501bad999bfe943c08f050235d7d68b1da55e63f73b60a57fce"),
        PBKDF2Case(password: "password", salt: "salt", iterations: 4096, length: 64, out: "d197b1b33db0143e018b12f3d1d1479e6cdebdcc97c5c0f87f6902e072f457b5143f30602641b3d55cd335988cb36b84376060ecd532e039b742a239434af2d5"),
        PBKDF2Case(password: "mnemonic-pass", salt: "mnemonic", iterations: 2, length: 32, out: "c52c6ba74386faa802eb82d5eab8813ac68dd6e92e708e46b582cdad636eded4"),
    ]
}
