// Generated by tools/gen_vault_vectors.py — do not edit by hand.
// Reference values produced independently with Python's `cryptography` package.

import Foundation

enum VaultVectors {
    static let password = "correct horse battery staple"
    static let iterations = 1000
    static let salt = Data(hex: "0101010101010101010101010101010101010101010101010101010101010101")!
    static let nonce = Data(hex: "020202020202020202020202")!
    static let masterKey = Data(hex: "0303030303030303030303030303030303030303030303030303030303030303")!
    static let kek = Data(hex: "b95321b1b66f772229ab6a8c27d42400bc773621d5d3bb8647dfec3c53cb4d0a")!
    static let wrapAAD = Data(hex: "53656e74696e656c5661756c742d7631000003e80101010101010101010101010101010101010101010101010101010101010101")!
    static let wrappedMasterCiphertext = Data(hex: "7f969b82c685efec17717a201795c3c58505356a8a671e79d9b8b355bad189dc")!
    static let wrappedMasterTag = Data(hex: "d96e54981791f86114521a3c80b982d9")!
    static let itemID = "3f1a6c2e-9b47-4f0d-8a2e-51c8f0b7d5a1"
    static let itemNonce = Data(hex: "040404040404040404040404")!
    static let itemAAD = Data(hex: "53656e74696e656c5661756c744974656d2d763133663161366332652d396234372d346630642d386132652d353163386630623764356131")!
    static let itemPlaintext = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
    static let itemCiphertext = Data(hex: "214572a3c9f1693ef876e130153b5750f01eee0227ac29c2490a66ff47e1877cc21b55b2253c86677850e17249db82b6c8337a8ba7c2a5189fb7caec331876f3076c08e70b738a7e03af889a4ceb68b26c083c6de8f74716e33dc69f52")!
    static let itemTag = Data(hex: "031cd9904e793ac9ef8360456c55889a")!
}
