#!/usr/bin/env python3
"""
Writes the reference vectors produced by tools/vectors.py into the iOS project:

    ios/docs/vectors.json                                  (machine readable)
    ios/docs/vectors.md                                    (documented, for humans)
    ios/Tests/SentinelWalletCoreTests/TestVectors.swift     (used by the Swift tests)

Run it after changing tools/vectors.py:

    python3 tools/gen_ios_vectors.py
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "ios"


def main():
    raw = subprocess.run([sys.executable, str(ROOT / "tools" / "vectors.py"), "--json"],
                         capture_output=True, text=True, check=True).stdout
    v = json.loads(raw)

    (OUT / "docs").mkdir(parents=True, exist_ok=True)
    (OUT / "Tests" / "SentinelWalletCoreTests").mkdir(parents=True, exist_ok=True)
    (OUT / "docs" / "vectors.json").write_text(json.dumps(v, indent=2) + "\n")

    # ---------------------------------------------------------------- markdown
    md = ["# Reference vectors", "",
          "Generated by `tools/gen_ios_vectors.py` from `tools/vectors.py` — an independent, pure-Python",
          "implementation of BIP-39 / BIP-32 / BIP-44 / BIP-49 / BIP-84 / BIP-86 / SLIP-10 / EIP-55 / BIP-173",
          "that reads the same word list the app ships (`app/bip39.txt`).", "",
          "The Swift tests in `ios/Tests/SentinelWalletCoreTests` assert against these numbers, so a",
          "regression in the crypto layer fails the build.", "",
          "## Word list", "",
          f"* words: **{v['wordlist']['count']}**",
          f"* first / last: `{v['wordlist']['first']}` … `{v['wordlist']['last']}`",
          f"* `about` index: {v['wordlist']['index_about']} · `zoo` index: {v['wordlist']['index_zoo']}",
          f"* sha256 of the newline-joined list: `{v['wordlist']['sha256']}`", "",
          "## BIP-39", "",
          "| mnemonic | passphrase | seed |",
          "|---|---|---|",
          f"| abandon ×11 + about | TREZOR | `{v['bip39_seed']['seed']}` |",
          f"| abandon ×11 + about | (none) | `{v['bip39_seed_no_passphrase']['seed']}` |", "",
          "## BIP-32", "",
          f"* master xprv (seed 000102…0f): `{v['bip32_vector1']['master_xprv']}`",
          f"* master xpub: `{v['bip32_vector1']['master_xpub']}`",
          f"* m/0' xprv: `{v['bip32_vector1_child']['xprv']}`",
          "* seed fffcf9f6…4542 master xpub: `" + v["bip32_vector2"]["master_xpub"] + "`", "",
          "## Addresses from `abandon ×11 + about`", "",
          "| standard | path | address |",
          "|---|---|---|",
          f"| BIP-44 legacy P2PKH | {v['bip44_btc']['path']} | `{v['bip44_btc']['address']}` |",
          f"| BIP-49 P2SH-P2WPKH | {v['bip49_btc']['path']} | `{v['bip49_btc']['address']}` |",
          f"| BIP-84 native segwit | {v['bip84_btc']['path']} | `{v['bip84_btc']['address']}` |",
          f"| BIP-86 taproot | {v['bip86_btc']['path']} | `{v['bip86_btc']['address']}` |",
          f"| Ethereum / EVM (EIP-55) | {v['bip44_eth']['path']} | `{v['bip44_eth']['address']}` |",
          f"| Solana (ed25519) | {v['bip44_sol']['path']} | `{v['bip44_sol']['address']}` |", "",
          "## Hashes", "",
          "| input | keccak-256 |", "|---|---|"]
    for k in v["keccak256"]:
        md.append(f"| `{k['input'][:46] or '(empty)'}` | `{k['out']}` |")
    md += ["", "| input | ripemd-160 |", "|---|---|"]
    for k in v["ripemd160"]:
        md.append(f"| `{k['input'] or '(empty)'}` | `{k['out']}` |")
    md += ["", "## Credential import", "",
           f"* WIF (uncompressed, m/44'/0'/0'/0/0): `{v['private_keys']['wif_mainnet']}`",
           f"* WIF (compressed): `{v['private_keys']['wif_compressed']}`",
           f"* raw hex private key: `{v['private_keys']['hex']}`", ""]
    (OUT / "docs" / "vectors.md").write_text("\n".join(md))

    # ---------------------------------------------------------------- swift constants
    def swift_str(value):
        """Python value -> Swift literal, with control characters escaped the Swift way."""
        if value is None:
            return "nil"
        if isinstance(value, bool):
            return "true" if value else "false"
        text = json.dumps(value, ensure_ascii=False)
        out = []
        for ch in text:
            if ch == "\u007f" or (ord(ch) < 0x20):
                out.append("\\u{%x}" % ord(ch))
            else:
                out.append(ch)
        return "".join(out)

    def swift_str_list(name, items):
        inner = ",\n        ".join(swift_str(i) for i in items)
        return f"    static let {name}: [String] = [\n        {inner},\n    ]\n"

    def swift_pairs(name, items, key1, key2):
        rows = ",\n        ".join(f"({swift_str(i[key1])}, {swift_str(i[key2])})" for i in items)
        return f"    static let {name}: [(String, String)] = [\n        {rows},\n    ]\n"

    s = ['// Generated by tools/gen_ios_vectors.py — do not edit by hand.',
         '// Independent reference values for the crypto layer (see ios/docs/vectors.md).',
         'import Foundation',
         '',
         'enum TestVectors {']
    s.append('    static let mnemonic = ' + json.dumps(v["bip39_seed"]["mnemonic"]))
    s.append('    static let passphrase = "TREZOR"')
    s.append('    static let seedTrezor = ' + json.dumps(v["bip39_seed"]["seed"]))
    s.append('    static let seedNoPassphrase = ' + json.dumps(v["bip39_seed_no_passphrase"]["seed"]))
    s.append('    static let wordlistSHA256 = ' + json.dumps(v["wordlist"]["sha256"]))
    s.append('    static let wordlistFirst = ' + json.dumps(v["wordlist"]["first"]))
    s.append('    static let wordlistLast = ' + json.dumps(v["wordlist"]["last"]))
    s.append('    static let indexAbout = ' + str(v["wordlist"]["index_about"]))

    s.append('\n    // MARK: BIP-32')
    s.append('    static let bip32Seed1 = ' + json.dumps(v["bip32_vector1"]["seed"]))
    s.append('    static let bip32MasterXprv = ' + json.dumps(v["bip32_vector1"]["master_xprv"]))
    s.append('    static let bip32MasterXpub = ' + json.dumps(v["bip32_vector1"]["master_xpub"]))
    s.append('    static let bip32MasterChainCode = ' + json.dumps(v["bip32_vector1"]["chain_code"]))
    s.append('    static let bip32MasterPrivHex = ' + json.dumps(v["bip32_vector1"]["private_key"]))
    s.append('    static let bip32ChildXprv = ' + json.dumps(v["bip32_vector1_child"]["xprv"]))
    s.append('    static let bip32ChildXpub = ' + json.dumps(v["bip32_vector1_child"]["xpub"]))
    s.append('    static let bip32Vector2MasterXpub = ' + json.dumps(v["bip32_vector2"]["master_xpub"]))

    s.append('\n    // MARK: BIP-32 test vector 1, deeper chains (hardened and normal steps)')
    s.append('    static let bip32DeepChain: [(path: String, xprv: String, xpub: String)] = [')
    for row in v["bip32_vector1_deep"]:
        s.append(f'        ({json.dumps(row["path"])}, {json.dumps(row["xprv"])}, {json.dumps(row["xpub"])}),')
    s.append('    ]')

    s.append('\n    // MARK: addresses for the abandon…about mnemonic')
    for key, name in (("bip44_btc", "btcLegacy"), ("bip49_btc", "btcP2SH"), ("bip84_btc", "btcSegwit"),
                      ("bip86_btc", "btcTaproot"), ("bip44_eth", "eth"), ("bip44_sol", "solana")):
        s.append(f'    static let {name}Address = ' + json.dumps(v[key]["address"]))
        s.append(f'    static let {name}Path = ' + json.dumps(v[key]["path"]))
    s.append('    static let btcTaprootOutputKey = ' + json.dumps(v["bip86_output_key"]))
    s.append('    static let bip84AccountXprv = ' + json.dumps(v["bip84_btc"]["account_xprv"]))
    s.append('    static let bip84AccountXpub = ' + json.dumps(v["bip84_btc"]["account_xpub"]))
    s.append('    static let bip84Hash160 = ' + json.dumps(v["bip84_btc"]["hash160"]))
    s.append('    static let wif = ' + json.dumps(v["private_keys"]["wif_mainnet"]))
    s.append('    static let wifCompressed = ' + json.dumps(v["private_keys"]["wif_compressed"]))
    s.append('    static let privHex = ' + json.dumps(v["private_keys"]["hex"]))

    s.append('\n    // MARK: hashes')
    s.append(swift_pairs("keccak", v["keccak256"], "input", "out").rstrip())
    s.append('')
    s.append(swift_pairs("ripemd", v["ripemd160"], "input", "out").rstrip())
    s.append('')
    s.append(swift_pairs("sha256", v["sha256"], "input", "out").rstrip())
    s.append('')
    s.append(swift_pairs("sha512", v["sha512"], "input", "out").rstrip())
    s.append('')
    s.append('')
    s.append('\n    // MARK: base58check')
    s.append('    static let base58check = (version: ' + swift_str(v["base58check"][0]["version"]) +
             ', payload: ' + swift_str(v["base58check"][0]["payload"]) +
             ', out: ' + swift_str(v["base58check"][0]["out"]) + ')')

    s.append('\n    // MARK: bech32 (BIP-173 reference lists)')
    s.append('')
    s.append(swift_str_list("bech32Valid", v["bech32_valid"]).rstrip())
    s.append('')
    s.append(swift_str_list("bech32Invalid", v["bech32_invalid"]).rstrip())
    s.append('')
    s.append('    // MARK: credential parsing')
    s.append('')
    s.append('    struct PhraseCase: Sendable { let phrase: String; let valid: Bool; let reason: String? }')
    rows = ",\n        ".join(
        f'PhraseCase(phrase: {swift_str(c["phrase"])}, valid: {"true" if c["valid"] else "false"}, '
        f'reason: {swift_str(c.get("reason"))})' for c in v["bip39_validate"])
    s.append(f'    static let phraseCases: [PhraseCase] = [\n        {rows},\n    ]')
    s.append('')
    s.append('    // MARK: pbkdf2-hmac-sha512')
    s.append('')
    s.append('    struct PBKDF2Case: Sendable { let password: String; let salt: String; let iterations: Int; let length: Int; let out: String }')
    rows = ",\n        ".join(
        f'PBKDF2Case(password: {swift_str(c["password"])}, salt: {swift_str(c["salt"])}, '
        f'iterations: {c["iterations"]}, length: {c["dklen"]}, out: {json.dumps(c["out"])})'
        for c in v["pbkdf2"])
    s.append(f'    static let pbkdf2Cases: [PBKDF2Case] = [\n        {rows},\n    ]')
    s.append('}')
    (OUT / "Tests" / "SentinelWalletCoreTests" / "TestVectors.swift").write_text("\n".join(s) + "\n")

    print("wrote ios/docs/vectors.json, ios/docs/vectors.md, ios/Tests/SentinelWalletCoreTests/TestVectors.swift")


if __name__ == "__main__":
    main()
