#!/usr/bin/env python3
"""Regenerates ios/Core/Wallet/BIP39Wordlist.swift from app/bip39.txt."""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
WORDS = (ROOT / "app" / "bip39.txt").read_text().split()
assert len(WORDS) == 2048 and len(set(WORDS)) == 2048, "app/bip39.txt is not the 2,048-word list"

rows = []
for i in range(0, 2048, 16):
    rows.append("        " + ", ".join('"%s"' % w for w in WORDS[i:i + 16]) + ",")

sha = __import__("hashlib").sha256("\n".join(WORDS).encode()).hexdigest()
swift = f'''// Generated by tools/gen_wordlist_swift.py from app/bip39.txt — do not edit by hand.
//
// The official BIP-39 English word list, exactly as shipped in the SENTINEL repo
// (app/bip39.txt). 2,048 words, sorted, unique. The sha256 of the newline-joined
// list is asserted in the test suite.

import Foundation

public enum BIP39Wordlist {{
    /// All 2,048 words in canonical order (abandon … zoo).
    public static let words: [String] = [
{chr(10).join(rows)}
    ]

    /// word -> index lookup, built once.
    public static let indexOf: [String: Int] = {{
        var map = [String: Int](minimumCapacity: 2048)
        for (i, w) in words.enumerated() {{ map[w] = i }}
        return map
    }}()

    public static let count = 2048

    /// sha256 of the words joined by newlines — matches the reference vector.
    public static let canonicalSHA256 = "{sha}"

    /// True when the list really is the canonical one (count, order, uniqueness).
    public static func isCanonical() -> Bool {{
        guard words.count == 2048, indexOf.count == 2048 else {{ return false }}
        let joined = words.joined(separator: "\\n")
        guard let data = joined.data(using: .utf8) else {{ return false }}
        return SHA256.hash(data).hexString == canonicalSHA256
    }}
}}
'''
(ROOT / "ios" / "Core" / "Wallet" / "BIP39Wordlist.swift").write_text(swift)
print(f"wrote BIP39Wordlist.swift ({len(WORDS)} words, sha256 {sha[:16]}…)")
