#!/usr/bin/env python3
"""Independent reference for the Sentinel vault envelope.

PBKDF2-HMAC-SHA512 + AES-256-GCM over a wrapped master key, then per-item sealing.
Everything here is computed with the `cryptography` package so the Swift vault can be
checked against a second implementation rather than against itself.
"""
import json, pathlib, hashlib
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes

PASSWORD = "correct horse battery staple"
SALT = bytes([0x01]) * 32          # fixed for the vector
NONCE = bytes([0x02]) * 12
MASTER = bytes([0x03]) * 32
ITEM_ID = "3f1a6c2e-9b47-4f0d-8a2e-51c8f0b7d5a1"
ITEM_NONCE = bytes([0x04]) * 12
ITEM_PLAINTEXT = b"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
ITERATIONS = 1000

kek = PBKDF2HMAC(algorithm=hashes.SHA512(), length=32, salt=SALT, iterations=ITERATIONS).derive(PASSWORD.encode())

WARP_AAD = b"SentinelVault-v1" + ITERATIONS.to_bytes(4, "big") + SALT
wrapped = AESGCM(kek).encrypt(NONCE, MASTER, WARP_AAD)
wrapped_ct, wrapped_tag = wrapped[:-16], wrapped[-16:]

ITEM_AAD = b"SentinelVaultItem-v1" + ITEM_ID.encode()
item = AESGCM(MASTER).encrypt(ITEM_NONCE, ITEM_PLAINTEXT, ITEM_AAD)
item_ct, item_tag = item[:-16], item[-16:]

v = {
    "password": PASSWORD,
    "iterations": ITERATIONS,
    "salt": SALT.hex(),
    "nonce": NONCE.hex(),
    "master_key": MASTER.hex(),
    "kek": kek.hex(),
    "wrap_aad": WARP_AAD.hex(),
    "wrapped_master_ct": wrapped_ct.hex(),
    "wrapped_master_tag": wrapped_tag.hex(),
    "item_id": ITEM_ID,
    "item_nonce": ITEM_NONCE.hex(),
    "item_aad": ITEM_AAD.hex(),
    "item_plaintext": ITEM_PLAINTEXT.decode(),
    "item_ct": item_ct.hex(),
    "item_tag": item_tag.hex(),
}
pathlib.Path("ios/docs/vault.json").write_text(json.dumps(v, indent=2) + "\n")

swift = [
    "// Generated by tools/gen_vault_vectors.py — do not edit by hand.",
    "// Reference values produced independently with Python's `cryptography` package.",
    "",
    "import Foundation",
    "",
    "enum VaultVectors {",
    f'    static let password = {json.dumps(v["password"])}',
    f'    static let iterations = {v["iterations"]}',
    f'    static let salt = Data(hex: {json.dumps(v["salt"])})!',
    f'    static let nonce = Data(hex: {json.dumps(v["nonce"])})!',
    f'    static let masterKey = Data(hex: {json.dumps(v["master_key"])})!',
    f'    static let kek = Data(hex: {json.dumps(v["kek"])})!',
    f'    static let wrapAAD = Data(hex: {json.dumps(v["wrap_aad"])})!',
    f'    static let wrappedMasterCiphertext = Data(hex: {json.dumps(v["wrapped_master_ct"])})!',
    f'    static let wrappedMasterTag = Data(hex: {json.dumps(v["wrapped_master_tag"])})!',
    f'    static let itemID = {json.dumps(v["item_id"])}',
    f'    static let itemNonce = Data(hex: {json.dumps(v["item_nonce"])})!',
    f'    static let itemAAD = Data(hex: {json.dumps(v["item_aad"])})!',
    f'    static let itemPlaintext = {json.dumps(v["item_plaintext"])}',
    f'    static let itemCiphertext = Data(hex: {json.dumps(v["item_ct"])})!',
    f'    static let itemTag = Data(hex: {json.dumps(v["item_tag"])})!',
    "}",
    "",
]
pathlib.Path("ios/Tests/SentinelWalletCoreTests/VaultVectors.swift").write_text("\n".join(swift))
print("KEK:", kek.hex())
print("wrapped master:", wrapped_ct.hex(), "+", wrapped_tag.hex())
print("item ct:", item_ct.hex(), "+", item_tag.hex())
